name: Collect Weather

on:
  workflow_dispatch:
    inputs:
      city:
        description: "City name"
        required: false
        default: "London"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run collector
        run: python -m src.collect --city "${{ github.event.inputs.city }}"
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-csv
          path: data/*.csv
